{"id":null,"jsonrpc":"2.0","method":"textDocument/extendPublishDiagnostics","params":{"diagnostics":[{"category":74,"code":74,"message":"undeclared type name 'RefArray'","range":{"end":{"character":20,"line":7},"start":{"character":19,"line":7}},"severity":1,"source":"Cangjie"},{"category":75,"code":75,"message":"undeclared identifier 'RefArray'","range":{"end":{"character":38,"line":7},"start":{"character":37,"line":7}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RefArray'","range":{"end":{"character":20,"line":15},"start":{"character":19,"line":15}},"severity":1,"source":"Cangjie"},{"category":75,"code":75,"message":"undeclared identifier 'RefArray'","range":{"end":{"character":38,"line":15},"start":{"character":37,"line":15}},"severity":1,"source":"Cangjie"},{"category":727,"code":727,"message":"'getMessage' is not a member of class 'Error'","range":{"end":{"character":49,"line":19},"start":{"character":39,"line":19}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RefArray'","range":{"end":{"character":20,"line":23},"start":{"character":19,"line":23}},"severity":1,"source":"Cangjie"},{"category":75,"code":75,"message":"undeclared identifier 'RefArray'","range":{"end":{"character":38,"line":23},"start":{"character":37,"line":23}},"severity":1,"source":"Cangjie"},{"category":186,"code":186,"message":"the exception catch type must be class and extends from core.Exception or core.Error","range":{"end":{"character":18,"line":26},"start":{"character":17,"line":26}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'Throwable'","range":{"end":{"character":18,"line":26},"start":{"character":17,"line":26}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RefArray'","range":{"end":{"character":20,"line":31},"start":{"character":19,"line":31}},"severity":1,"source":"Cangjie"},{"category":75,"code":75,"message":"undeclared identifier 'RefArray'","range":{"end":{"character":38,"line":31},"start":{"character":37,"line":31}},"severity":1,"source":"Cangjie"},{"category":727,"code":727,"message":"'getMessage' is not a member of class 'Exception'","range":{"end":{"character":49,"line":35},"start":{"character":39,"line":35}},"severity":1,"source":"Cangjie"},{"category":588,"code":588,"message":"'main' declaration doesn't need 'func' keyword","range":{"end":{"character":9,"line":39},"start":{"character":5,"line":39}},"severity":1,"source":"Cangjie"},{"category":186,"code":186,"message":"the exception catch type must be class and extends from core.Exception or core.Error","range":{"end":{"character":17,"line":42},"start":{"character":16,"line":42}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RuntimeException'","range":{"end":{"character":17,"line":42},"start":{"character":16,"line":42}},"severity":1,"source":"Cangjie"},{"category":727,"code":727,"message":"'getMessage' is not a member of class 'Father'","range":{"end":{"character":26,"line":82},"start":{"character":16,"line":82}},"severity":1,"source":"Cangjie"},{"category":186,"code":186,"message":"the exception catch type must be class and extends from core.Exception or core.Error","range":{"end":{"character":17,"line":91},"start":{"character":16,"line":91}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RuntimeException'","range":{"end":{"character":17,"line":91},"start":{"character":16,"line":91}},"severity":1,"source":"Cangjie"},{"category":186,"code":186,"message":"the exception catch type must be class and extends from core.Exception or core.Error","range":{"end":{"character":17,"line":102},"start":{"character":16,"line":102}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RuntimeException'","range":{"end":{"character":17,"line":102},"start":{"character":16,"line":102}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RefArray'","range":{"end":{"character":20,"line":112},"start":{"character":19,"line":112}},"severity":1,"source":"Cangjie"},{"category":75,"code":75,"message":"undeclared identifier 'RefArray'","range":{"end":{"character":38,"line":112},"start":{"character":37,"line":112}},"severity":1,"source":"Cangjie"},{"category":727,"code":727,"message":"'getMessage' is not a member of class 'ArithmeticException'","range":{"end":{"character":64,"line":117},"start":{"character":54,"line":117}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'Throwable'","range":{"end":{"character":46,"line":123},"start":{"character":45,"line":123}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'Throwable'","range":{"end":{"character":26,"line":126},"start":{"character":25,"line":126}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'Throwable'","range":{"end":{"character":46,"line":126},"start":{"character":45,"line":126}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'Throwable'","range":{"end":{"character":27,"line":127},"start":{"character":26,"line":127}},"severity":1,"source":"Cangjie"},{"category":183,"code":183,"message":"generic type should be used with type argument","range":{"end":{"character":40,"line":127},"start":{"character":39,"line":127}},"severity":1,"source":"Cangjie"},{"category":74,"code":74,"message":"undeclared type name 'RefArray'","range":{"end":{"character":20,"line":129},"start":{"character":19,"line":129}},"severity":1,"source":"Cangjie"},{"category":75,"code":75,"message":"undeclared identifier 'RefArray'","range":{"end":{"character":38,"line":129},"start":{"character":37,"line":129}},"severity":1,"source":"Cangjie"},{"category":727,"code":727,"message":"'getMessage' is not a member of class 'Exception'","range":{"end":{"character":47,"line":133},"start":{"character":37,"line":133}},"severity":1,"source":"Cangjie"},{"category":727,"code":727,"message":"'getMessage' is not a member of class 'Exception'","range":{"end":{"character":110,"line":135},"start":{"character":100,"line":135}},"severity":1,"source":"Cangjie"}],"uri":"file://***//lsp/test/testChr/normalTest/Exception/src/exception.cj"}}